import { StyleSheet, Dimensions, Platform } from "react-native";

const { width, height } = Dimensions.get("window");

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F2F2F2",
  },
  map: {
    width: width,
    height: height,
    ...Platform.select({
      ios: {
        marginTop: 0,
      },
      android: {
        marginTop: 0,
      },
    }),
  },
  inputContainer: {
    position: "absolute",
    top: Platform.select({
      ios: height * 0.06,
      android: height * 0.04,
    }),
    left: width * 0.05,
    width: width * 0.9,
    backgroundColor: "#ffffff",
    borderRadius: 15,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 5,
    height: Platform.select({
      ios: 50,
      android: 50,
    }),
    zIndex: 10,
  },
  input: {
    flex: 1,
    fontSize: width > 400 ? 16 : 14,
    paddingLeft: 10,
    color: "#333",
  },
  addressContainer: {
    position: "absolute",
    bottom: height * 0.02,
    left: width * 0.05,
    width: width * 0.9,
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    borderRadius: 10,
    padding: width > 400 ? 15 : 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 3,
    alignItems: "center",
    zIndex: 10,
  },
  addressText: {
    fontSize: width > 400 ? 15 : 13,
    color: "#333",
    textAlign: "center",
    fontWeight: "600",
  },
  waitMapText: {
    flex: 1,
    textAlign: "center",
    fontSize: width > 400 ? 16 : 14,
    color: "#555",
    paddingTop: height * 0.3,
  },
  searchContainer: {
    position: "absolute",
    top: Platform.select({
      ios: height * 0.06,
      android: height * 0.04,
    }),
    left: width * 0.05,
    width: width * 0.9,
    backgroundColor: "#fff",
    borderRadius: 15,
    paddingHorizontal: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 5,
    zIndex: 10,
  },
  searchInput: {
    height: Platform.select({
      ios: 45,
      android: 45,
    }),
    fontSize: width > 400 ? 16 : 14,
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 15,
    backgroundColor: '#fff',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F2F2F2',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    backgroundColor: '#F2F2F2',
  },
  errorText: {
    fontSize: width > 400 ? 16 : 14,
    marginBottom: 20,
    color: 'red',
    textAlign: 'center',
  },
  retryButton: {
    padding: 12,
    backgroundColor: '#1A7526', // Cor verde alinhada com o tema
    borderRadius: 8,
    minWidth: width * 0.4,
    alignItems: 'center',
  },
  retryButtonText: {
    color: '#fff',
    fontSize: width > 400 ? 16 : 14,
    fontWeight: '600',
  },
  // Novos estilos para o modal de propriedade
  propertyModalContainer: {
    position: 'absolute',
    bottom: height * 0.02,
    left: width * 0.05,
    width: width * 0.9,
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    zIndex: 20,
  },
  propertyImage: {
    width: '100%',
    height: 150,
    borderRadius: 8,
    marginBottom: 10,
  },
  propertyTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1A7526',
    marginBottom: 5,
  },
  propertyPrice: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 8,
  },
  propertyDetailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 5,
  },
  propertyDetailText: {
    fontSize: 14,
    color: '#555',
  },
  propertyAddress: {
    fontSize: 13,
    color: '#666',
    marginTop: 8,
    fontStyle: 'italic',
  },
  closeButton: {
    position: 'absolute',
    top: 10,
    right: 10,
    padding: 5,
    backgroundColor: 'rgba(0,0,0,0.2)',
    borderRadius: 15,
  },
  viewDetailsButton: {
    backgroundColor: '#1A7526',
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 10,
  },
  viewDetailsButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 15,
  },
});

export default styles;